name: Sync local main
on:
  push:
    branches: [master] # fires on push to master

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - name: Pull latest master
        run: |
          cd /Users/tungdangtran/Documents/RedBookScala/
          git fetch origin master
          git reset --hard origin/master
